### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by wallace11** [ozmartian/tvlinker#1]
I'm mainly using Python 2, so in order to install this I head to install Python 3 and pip3 from scratch.
There, I faced some missing modules that were not requested originally by `pip3 install tvlinker`. I had to install them manually one by one.

- requests
- hurry.filesize

System:
Ubuntu Xenial x64

**Comment by morfikov** [comment]
When I installed tvlinker on Debian, I got this:

```
$ tvlinker
Traceback (most recent call last):
  File "/usr/bin/tvlinker", line 11, in <module>
    load_entry_point('tvlinker==4.0.5', 'gui_scripts', 'tvlinker')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/tvlinker/__main__.py", line 36, in <module>
    import tvlinker.notify as notify
  File "/usr/lib/python3/dist-packages/tvlinker/notify.py", line 38, in <module>
    import dbus
ImportError: No module named 'dbus'
```

It looks like the `python3-dbus` dependency is missing. tvlinker works fine after I manually installed it.
