### ISSUE TITLE
Crash on launch on openSUSE

### ISSUE THREAD

**Issue by lgbaldoni** [ozmartian/tvlinker#4]
I'm trying to package for openSUSE Tumbleweed, but this is what I see on launch:
```
> tvlinker 
Traceback (most recent call last):
  File "/usr/bin/tvlinker", line 11, in <module>
    load_entry_point('tvlinker==4.0.0.post5', 'gui_scripts', 'tvlinker')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/tvlinker/__main__.py", line 25, in <module>
    from tvlinker.threads import Aria2Thread, DownloadThread, HostersThread, RealDebridThread, ScrapeWorker
  File "/usr/lib/python3.6/site-packages/tvlinker/threads.py", line 17, in <module>
    import tvlinker.cfscrape as cfscrape
  File "/usr/lib/python3.6/site-packages/tvlinker/cfscrape.py", line 8, in <module>
    import tvlinker.js2py as js2py
ModuleNotFoundError: No module named 'tvlinker.js2py'
```

As far as I can see, every dependency is available, including Js2Py (which I'm not even sure is actually needed).

Am I doing something wrong?

**Comment by lgbaldoni** [comment]
Update: using the tarball from github instead of the pypi one solved the problem.
Perhaps the latter could use an update.

**Comment by ozmartian** [comment]
apologies... Pypi hasn't been updated in a loooong while... stick to the Github repo as i dont maintain this very much at all these days
